"""Bot-facing Crowd Control API.

Bots import everything they need from :mod:`melee.bot` rather than the
``crowd_control`` runtime package. This keeps the bot author surface small and
self-contained: a bot file + libmelee is sufficient to develop and type-check
against.
"""

from melee.bot.anonymous_input_montage import AnonymousInputMontage
from melee.bot.base_bot import BaseBot
from melee.bot.character_state import (
    AttackType,
    CharacterState,
    CharacterStatus,
    GroundDodgeStickReferenceAxis,
    HorizontalStickReferenceAxis,
    attack_is_holdable,
    can_air_attack,
    can_airdodge,
    can_attack,
    can_dodge,
    can_grab,
    can_jump,
    can_shield,
    can_taunt,
    can_z_air,
    get_state,
    in_hitstun,
    is_carrying_enemy,
    is_dodging,
    is_downed,
    is_getting_up,
    is_grabbed,
    is_grabbing,
    is_grabbing_ledge,
    is_shield_broken,
    is_shielding,
    is_taunting,
    neutral_b_is_chargeable,
    z_air_is_supported,
)
from melee.bot.input_montage import Abort, InputMontage, MontageState, PreTickResult
from melee.bot.listener import Listener, ListenerOrCallable, Listeners, SimpleListener
from melee.bot.logger import BotLogEntry, BotLogger
from melee.bot.match_history import (
    MatchHistory,
    MatchRoundOutcome,
    OtherPlayer,
    OtherPlayerRelation,
    PlayerMatchRecord,
)
from melee.bot.protocol import BotProtocol, CharacterSelection, CrowdControl
from melee.bot.simple_controls import (
    AttackFrameData,
    Hold,
    LedgeRecoveryOption,
    SimpleControls,
    StickReferenceAxis,
    stick_coordinates,
)
from melee.bot.stateful_input_montage import StatefulInputMontage
from melee.bot.strategy import Continue, Exit, Strategy
from melee.bot.techskill import (
    InitiateDashMontage,
    LedgedashMontage,
    MultishineMontage,
    PerfectPivotMontage,
    SDIMontage,
    SmashTurnJumpMontage,
    WavedashDirection,
    WavedashMontage,
)

__all__ = [
    "AnonymousInputMontage",
    "Abort",
    "AttackFrameData",
    "AttackType",
    "BaseBot",
    "BotLogEntry",
    "BotLogger",
    "BotProtocol",
    "CharacterSelection",
    "CharacterState",
    "CharacterStatus",
    "Continue",
    "CrowdControl",
    "Exit",
    "GroundDodgeStickReferenceAxis",
    "Hold",
    "HorizontalStickReferenceAxis",
    "InitiateDashMontage",
    "InputMontage",
    "LedgeRecoveryOption",
    "LedgedashMontage",
    "Listener",
    "ListenerOrCallable",
    "Listeners",
    "MatchHistory",
    "MatchRoundOutcome",
    "MontageState",
    "MultishineMontage",
    "OtherPlayer",
    "OtherPlayerRelation",
    "PerfectPivotMontage",
    "PlayerMatchRecord",
    "PreTickResult",
    "SDIMontage",
    "SimpleControls",
    "SimpleListener",
    "SmashTurnJumpMontage",
    "StatefulInputMontage",
    "StickReferenceAxis",
    "Strategy",
    "WavedashDirection",
    "WavedashMontage",
    "attack_is_holdable",
    "can_air_attack",
    "can_airdodge",
    "can_attack",
    "can_dodge",
    "can_grab",
    "can_jump",
    "can_shield",
    "can_taunt",
    "can_z_air",
    "get_state",
    "in_hitstun",
    "is_carrying_enemy",
    "is_dodging",
    "is_downed",
    "is_getting_up",
    "is_grabbed",
    "is_grabbing",
    "is_grabbing_ledge",
    "is_shield_broken",
    "is_shielding",
    "is_taunting",
    "neutral_b_is_chargeable",
    "stick_coordinates",
    "z_air_is_supported",
]
